apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: mywebserver
  name: mywebserver-service
  namespace: webservers
spec:
  selector:
    app: 
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000